language: ruby
rvm:
  - 1.9.3

before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "bundle exec rake test_app"

script:
  - "export DISPLAY=:99.0"
  - "bundle exec rspec spec"

branches:
  only:
    - 1-0-stable
    - master
